= ECMAScript
Pho Thin Mg <phothinmg@disroot.org>
:source-highlighter: highlight.js
:highlightjs-theme: monokai
:highlightjs-languages: js,ts
:toc: left
:favicon:
:tip-caption: 💡
:note-caption: 👉


== Brief Introduction

=== Ecma International

https://ecma-international.org/[Ecma International] သည် သတင်းအချက်အလက်နှင့် ဆက်သွယ်ရေးစနစ်များအတွက် အကျိုးအမြတ်မယူသော စံချိန်စံညွှန်းအဖွဲ့အစည်းတစ်ခုဖြစ်သည်။ ဥရောပရှိ ကွန်ပြူတာစနစ်များကို စံပြုရန် ၁၉၆၁ ခုနှစ်တွင် တည်ထောင်ခဲ့သည်။ ကွန်ပျူတာ သို့မဟုတ် ဆက်သွယ်ရေးစနစ်များကို ထုတ်လုပ်ခြင်း၊စျေးကွက်ချဲ့ထွင်ခြင်း၊နည်းပညာဆိုင်ရာ ကိုင်တွယ်ဖြေရှင်းသည့် နယ်ပယ်များတွင် စိတ်ပါဝင်စားမှုနှင့် အတွေ့အကြုံများရှိသည့် ကမ္ဘာတစ်ဝှမ်းရှိ ကုမ္ပဏီကြီးများနှင့် နည်းပညာဆိုင်ရာအဖွဲ့အစည်းများ ပါဝင်သည်။

Ecma သည် သတင်းအချက်အလက် ဆက်သွယ်ရေးနည်းပညာနှင့် လူသုံးအီလက်ထရွန်းနစ်ပစ္စည်းများကို အသုံးပြုရာတွင် အဆင်ပြေချောမွေ့စေရန်နှင့် စံချိန်စံညွှန်းသတ်မှတ်နိုင်ရန် စံချိန်စံညွှန်းများနှင့် နည်းပညာဆိုင်ရာ အစီရင်ခံစာများကို ဖွံ့ဖြိုးတိုးတက်စေရန် ရည်ရွယ်ပါသည်။ စံချိန်စံညွှန်းများအပါအဝင် Ecma ထုတ်ဝေမှုများကို မူပိုင်ခွင့်ကန့်သတ်ချက်များမပါဘဲ စိတ်ဝင်စားသူအားလုံးက လွတ်လပ်စွာကူးယူနိုင်ပါသည်။ နိုင်ငံအဆင့် စံသတ်မှတ်ရေး အဖွဲ့များနှင့် မတူဘဲ Ecma သည် အသင်းဝင် အခြေပြု ပြီး အကျိုးတူပူပေါင်း ဆောင်ရွက်သည့်အဖွဲ့အစည်း ဖြစ်သည်။ အများဆန္ဒအရ ရလဒ်များရရှိရန် ဗျူရိုကရေစီ လုပ်ငန်းစဉ်နည်းပါးခြင်းကြောင့် အချိန်တိုအတွင်း ပိုမိုကောင်းမွန်သော စံနှုန်းများ ထွက်ပေါ်လာစေသည်။ Ecma သည် သတင်းအချက်အလက်နည်းပညာနှင့် ဆက်သွယ်ရေးလုပ်ငန်းများတွင် ကမ္ဘာတစ်ဝှမ်း စံချိန်စံညွှန်းသတ်မှတ်ရေးတွင် တက်ကြွစွာ ပါဝင်ကူညီခဲ့သည်။

Ecma Standards 400 ကျော် Technical Reports 100 ကျော် ကို ထုတ်ဝေခဲ့ပြီး ၎င်းတို့ထဲမှ သုံးပုံ နှစ်ပုံကျော်ကို နိုင်ငံတကာစံနှုန်းများ, နည်းပညာဆိုင်ရာအစီရင်ခံစာများအဖြစ် လက်ခံကျင့်သုံးခဲ့သည်။

===  ECMAScript^®^

ECMAScript (အတိုကောက် ES) သည် https://en.wikipedia.org/wiki/Netscape[Netscape]  မှ https://en.wikipedia.org/wiki/Brendan_Eich[Brendan Eich] ဖန်တီးထားသော scripting language တစ်ခု၏ စံသတ်မှတ်ချက်တစ်ခုဖြစ်သည်။ 1995 ခုနှစ် ဒီဇင်ဘာလတွင် https://en.wikipedia.org/wiki/Sun_Microsystems[Sun Microsystems] နှင့် https://en.wikipedia.org/wiki/Netscape[Netscape] တို့သည် https://en.wikipedia.org/wiki/JavaScript[JavaScript] ကိုကြေငြာခဲ့သည်။ 1996 ခုနှစ် နိုဝင်ဘာလတွင် https://en.wikipedia.org/wiki/Netscape[Netscape] သည် https://en.wikipedia.org/wiki/JavaScript[JavaScript] ၏ စံသတ်မှတ်ချက်ကို မြှင့်တင်ရန်အတွက် https://ecma-international.org/[Ecma International] နှင့် တွေ့ဆုံဆွေးနွေးမှုအားကြေငြာခဲ့ပြီး https://ecma-international.org/publications-and-standards/standards/ecma-262/[ECMA-262] ထုတ်ဝေခြင်းအား 1997 ဇွန်လ တွင် Ecma အထွေထွေညီလာခံ မှကြေငြာခဲ့သည်။  https://ecma-international.org/publications-and-standards/standards/ecma-262/[ECMA-262] သည် https://shorturl.at/wmJuT[Ecma စံနှုန်းသတ်မှတ်ချက်များ] ထဲမှ https://en.wikipedia.org/wiki/JavaScript[JavaScript] ၏ စံနှုန်းသတ်မှတ်ချက်ဖြစ်သည်။

[NOTE]
__ECMAScript__^®^ __is__ __registered__ __trademarks__ __of__ https://ecma-international.org/[__Ecma International__].

[NOTE]
__JavaScript__^TM^ __is__ __a__ __trademark__ __of__ https://www.oracle.com/[__Oracle__].