= ECMAScript^®^ 2009,ES5
Pho Thin Mg <phothinmg@disroot.org>
:source-highlighter: highlight.js
:highlightjs-theme: monokai
:highlightjs-languages: js,ts
:toc: left
:toclevels: 4
:favicon: images/favicon.ico
:tip-caption: 💡
:note-caption: 👉
:sectnums:
:linkcss:
:nofooter:
:stylesdir: styles/
:stylesheet: index.css
:imagesdir: images/

== New Features

=== `"use strict"`

[playground]
'use strict' ; 
 x = 3.14 ; // x ကို declared မလုပ်သောကြောင့် error ဖြစ်ပါမည်
 console.log(x)

=== `String[number] access`

[playground]
const str = "HELLO WORLD";
console.log(str.charAt(0)); // returns H
console.log(str[0]); // returns H

=== `Multiline strings`

[source,js]
"Hello \
Dolly!";

=== `String.trim()`

`" example"` to `"example"`

[playground]
const str = " example";
console.log(str.trim()); //"example"

=== `Array.isArray()`

[playground]
const fruits = ["Banana", "Orange", "Apple", "Mango"];
console.log(Array.isArray(fruits)); // true

=== `Array.forEach()`

- return value : undefined

- originalArray : not modified after the method call

- newArray is not created after the end of method call.

[playground]
const nums = [1, 51, 22, "b", 57, 70, 10, 2, "a"];
const numUnder50 = [];
const numOver50 = [];
const notNum = [];
// ----
const test = nums.forEach(function (i) {
  if (typeof i !== "number") {
    notNum.push(i);
  } else if (i > 50) {
    numOver50.push(i);
  } else {
    numUnder50.push(i);
  }
});
console.log(notNum); // [ 'b', 'a' ]
console.log(numOver50); // [ 51, 57, 70 ]
console.log(numUnder50); // [ 1, 22, 10, 2 ]
console.log(test)// undefined

=== `Array.map()`

- return value : new Array populated with the results of calling a provided function on every element in the calling array

- originalArray : not modified after the method call

- newArray is created after the end of method call.

[playground]
const nums = [1, 2, 3, 4, 5];
const new_nums = nums.map((i) => i + 1);
console.log(nums); // [ 1, 2, 3, 4, 5 ]
console.log(new_nums); // [ 2, 3, 4, 5, 6 ]

=== `Array.filter()`

[playground]
const nums = [1, 2, 3, 4, 5];
const new_nums = nums.map((i) => i + 1);
console.log(nums); // [ 1, 2, 3, 4, 5 ]
console.log(new_nums); // [ 2, 3, 4, 5, 6 ]

=== `Array.filter()`

[playground]
const nums = [45, 4, 9, 16, 25];
const new_nums = nums.filter((i) => i > 20);
console.log(nums); // [ 45, 4, 9, 16, 25 ]
console.log(new_nums); // [ 45, 25 ]

=== `Array.reduce()`

=== `Array.reduceRight()`

=== `Array.every()`


script::"https://cdn.jsdelivr.net/gh/phothinmg/master-repo@main/jsplayground/index.min.js"[name="body"]